spring.datasource.url=jdbc:postgresql://localhost:5432/applytrack
spring.datasource.username=applytrack
spring.datasource.password=applytrack
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=false