spring.application.name=applytrack-api

spring.datasource.url=jdbc:h2:mem:applytrack
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
